namespace Neoxio.HlaSharp
{
    public enum ResignAction
    {
        UNCONDITIONALLY_DIVEST_ATTRIBUTES,
        DELETE_OBJECTS,
        CANCEL_PENDING_OWNERSHIP_ACQUISITIONS,
        DELETE_OBJECTS_THEN_DIVEST,
        CANCEL_THEN_DELETE_THEN_DIVEST,
        NO_ACTION
    }
}